import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  parseDataset,
  parseObservationFile,
  type DimensionName,
  type Observation,
} from '../packages/layout-knowledge/src/index';

/**
 * Turn the hospital dataset's own analysis into observations this repository can cite.
 *
 * > Owner decision: *"The uploaded drawing repository is now the primary source of planning
 * > knowledge. Extract actual planning knowledge from drawings … These become observed planning
 * > data, not manufacturer data."*
 * >
 * > *"The existing analysis blocks were generated by AI. Record them honestly as type: "ai", name:
 * > "MFD Hospital Dataset Analyzer", version: "1.0". Do not represent them as human observations."*
 *
 * ## What is extracted, and what is left alone
 *
 * Only `key_dimensions_mm` entries whose Korean annotation appears in {@link ANNOTATIONS}. The
 * dataset holds 2,916 such strings; **2,074 carry no annotation at all** — a bare `1160` states a
 * number and not what it measures, and a length with no subject cannot become a station pitch
 * without somebody deciding it is one. Those are counted and skipped.
 *
 * Of the annotated remainder, the mapping below is deliberately narrow. `베드 간격` and `베드 피치`
 * are unambiguous, and a room name like `간호사실` annotates a room dimension rather than a planning
 * distance — extracting those would need the width and depth paired, which the strings do not do.
 * The unmapped count is printed so the gap stays visible rather than becoming invisible progress.
 */

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATASET_ROOT = process.argv.includes('--dataset')
  ? (process.argv[process.argv.indexOf('--dataset') + 1] ?? '')
  : '/workspace/mfd-hospital-dataset';

/**
 * Korean annotation → the measurement it names.
 *
 * Each entry is a translation somebody can check, not an inference. `베드 간격` is "bed spacing",
 * `베드 피치` is "bed pitch", `통로 폭` is "passage width". Where a phrase could mean two things it
 * is left out, because a wrong mapping is worse than a smaller knowledge base: it produces a
 * confident figure under the wrong name and nothing downstream can tell.
 */
const ANNOTATIONS: Readonly<Record<string, DimensionName>> = {
  '베드 간격': 'station_pitch',
  '베드 피치': 'station_pitch',
  '베드 간격 주기': 'station_pitch',
  '베드 열 간격': 'station_row_spacing',
  '베드 열 간 간격': 'station_row_spacing',
  '열 간격': 'station_row_spacing',
  '하부 열 간격': 'station_row_spacing',
  '통로 폭': 'corridor_width',
  '통로': 'corridor_width',
};

/** `"8,150 (베드 열 길이)"` → 8150. Thousands separators appear in about half the strings. */
function millimetresOf(text: string): number | null {
  const match = /^\s*([\d,]+(?:\.\d+)?)/.exec(text);
  if (!match?.[1]) return null;
  const value = Number(match[1].replace(/,/g, ''));
  return Number.isFinite(value) && value > 0 ? value : null;
}

function annotationOf(text: string): string | null {
  const match = /\(([^)]*)\)/.exec(text);
  return match?.[1]?.trim() ?? null;
}

interface DatasetDrawing {
  hospital_id: string;
  file: string;
  revision: string | null;
  analysis: {
    legibility?: string | null;
    key_dimensions_mm?: string[] | null;
  } | null;
}

const drawings = (
  JSON.parse(readFileSync(join(DATASET_ROOT, 'metadata', 'drawings.json'), 'utf8')) as {
    drawings: DatasetDrawing[];
  }
).drawings;

// The catalogue carries the hash and the path — the two things that make an observation checkable.
const catalogue = new Map(
  parseDataset(
    JSON.parse(readFileSync(join(REPO, 'knowledge', 'dataset.json'), 'utf8')) as unknown,
  ).drawings.map((drawing) => [drawing.drawingId, drawing]),
);

/**
 * The analyst, named honestly.
 *
 * Not a person. The owner confirmed these readings were produced by a model, and the schema exists
 * so that fact travels with every figure derived from them rather than being lost at the boundary.
 */
const OBSERVER = {
  type: 'ai' as const,
  name: 'MFD Hospital Dataset Analyzer',
  version: '1.0',
};

const observations: Observation[] = [];
let unannotated = 0;
let unmapped = 0;
const unmappedNames = new Map<string, number>();

for (const drawing of drawings) {
  const drawingId = `${drawing.hospital_id}/${drawing.file}`;
  const catalogued = catalogue.get(drawingId);
  const dimensions = drawing.analysis?.key_dimensions_mm ?? [];
  if (!catalogued || dimensions.length === 0) continue;

  /*
   * The dataset's `legibility` becomes the observation's `confidence`, unchanged. Both use
   * high/medium/low, which is why the vocabulary was chosen — a reading recorded as "medium" by the
   * analyst stays "medium" here rather than being mapped onto a scale invented at the boundary.
   */
  const legibility = drawing.analysis?.legibility;
  const confidence =
    legibility === 'high' || legibility === 'medium' || legibility === 'low' ? legibility : 'low';

  dimensions.forEach((text, index) => {
    const annotation = annotationOf(text);
    if (annotation === null) {
      unannotated += 1;
      return;
    }

    const name = ANNOTATIONS[annotation];
    if (!name) {
      unmapped += 1;
      unmappedNames.set(annotation, (unmappedNames.get(annotation) ?? 0) + 1);
      return;
    }

    const millimetres = millimetresOf(text);
    if (millimetres === null) return;

    observations.push({
      id: `${drawingId}#${index}`,
      source: {
        drawing: {
          datasetId: 'dialysis-drawings',
          drawingId,
          path: catalogued.path,
          // Every drawing in this dataset is a single sheet; the analysis it came from is not
          // page-scoped, so there is no other page it could be.
          page: 0,
          sheet: null,
          revision: drawing.revision ?? null,
          sha256: catalogued.sha256,
        },
        // A printed dimension on the sheet, which is what `key_dimensions_mm` records.
        method: 'dimension_line',
        observer: OBSERVER,
        observationDate: '2026-07-31',
        confidence,
        note: `Dataset analysis, verbatim: "${text}"`,
      },
      value: {
        kind: 'common_dimension',
        name,
        millimetres,
        roomFunction: null,
      },
    });
  });
}

// Codepoint order — this writes a committed artefact, and `localeCompare` would make its bytes
// depend on the machine that generated them.
observations.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

const file = { datasetId: 'dialysis-drawings', observations };
parseObservationFile(file, 'knowledge/observations/hospital-dataset-analyzer.json');
writeFileSync(
  join(REPO, 'knowledge', 'observations', 'hospital-dataset-analyzer.json'),
  `${JSON.stringify(file, null, 2)}\n`,
  'utf8',
);

const byName = new Map<string, number>();
for (const observation of observations) {
  if (observation.value.kind === 'common_dimension') {
    byName.set(observation.value.name, (byName.get(observation.value.name) ?? 0) + 1);
  }
}

process.stdout.write(
  `observations: ${observations.length} extracted\n` +
    [...byName.entries()].sort().map(([name, count]) => `  ${name}: ${count}\n`).join('') +
    `skipped: ${unannotated} unannotated (a bare number states no subject), ` +
    `${unmapped} annotated but unmapped\n` +
    `  top unmapped: ${[...unmappedNames.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 8)
      .map(([name, count]) => `${name}(${count})`)
      .join(', ')}\n`,
);
